package com.mytitanplayer.bll;
// Generated Nov 28, 2012 7:52:45 PM by Hibernate Tools 3.2.1.GA


import java.util.*;

/**
 * Library generated by hbm2java
 */
public class Library  implements java.io.Serializable {


     private int songNum;
     private Users users;
     private String songName;
     private String songArtist;
     private String songAlbum;
     private String songPath;
     //private Set playlistses = new HashSet(0);
     private Set<Song> playlistses = new LinkedHashSet<Song>();

     //private Set<Song> mySongLibrary = new LinkedHashSet<Song>();        
     
     public int getSongCount(){
         return playlistses.size();
     }
     
     public Library() {
    }

    public void addNewSong(Song newSong){
            if(newSong != null){
                int libSize = playlistses.size();
                int lastSongNum = this.getLastSongNum();
                newSong.setSongNum(newSong, lastSongNum + 1);
                playlistses.add(newSong);
            }
    }
    
    public void removeSong(Song songToRemove) {
        playlistses.remove(songToRemove);
    }
    
    public int getSongLocation(Song playListSong){
        int songLocation = 0;
        List<Song> searchArray = new ArrayList<Song>(playlistses);
        //for(int i=0;i<searchArray.size();i++){
        if(searchArray.contains(playListSong)){
            songLocation = searchArray.indexOf(playListSong);
        }
        return songLocation;
    }        
 
    public Set sortByTitle() {
        SortedSet<String> sortSongs = new TreeSet<String>();
        List<Song> searchArray = new ArrayList<Song>(playlistses);
        //(new SongTitleComparator());
        String songStringByTitle = null;
        for(Song librarySong : searchArray){
            songStringByTitle = librarySong.showTitle(librarySong)+","+librarySong.showArtist(librarySong)+
                    ","+librarySong.showAlbum(librarySong)+","+librarySong.showPath(librarySong);
            sortSongs.add(songStringByTitle);
        }
        for(String songInfo : sortSongs){
            System.out.println(songInfo);
        }
        return sortSongs;
    }
    
    public Set sortByArtist() {
        SortedSet<String> sortSongs = new TreeSet<String>();
        List<Song> searchArray = new ArrayList<Song>(playlistses);
        //(new SongTitleComparator());
        String songStringByTitle = null;
        for(Song librarySong : searchArray){
            songStringByTitle = librarySong.showArtist(librarySong)+","+librarySong.showTitle(librarySong)+
                    ","+librarySong.showAlbum(librarySong)+","+librarySong.showPath(librarySong);
            sortSongs.add(songStringByTitle);
        }
        for(String songInfo : sortSongs){
            System.out.println(songInfo);
        }
        return sortSongs;
    }
    
    public void displaySongs(){
        
        List<Song> searchArray = new ArrayList<Song>(playlistses);
        
        for(Song thisSong : searchArray){
            System.out.println(thisSong.showSongNum(thisSong) + ", "
                    + thisSong.showTitle(thisSong) + ", "
                    + thisSong.showArtist(thisSong) +", "
                    + thisSong.showAlbum(thisSong) + ", "
                    + thisSong.showPath(thisSong));
        }
    }
    
    public String displayPlayListSong(int libraryLocation){
        String songInfo = "";
        List<Song> searchArray = new ArrayList<Song>(playlistses);
        Song selectedSong = searchArray.get(libraryLocation);
        songInfo = selectedSong.showTitle(selectedSong) + ", "
                + selectedSong.showArtist(selectedSong) +", "
                + selectedSong.showAlbum(selectedSong) + ", "
                + selectedSong.showPath(selectedSong);
        return songInfo;
    }
    
    public Library(int songNum, Users users, String songName, String songArtist, String songAlbum, String songPath) {
        //this.songNum = songNum;
        this.users = users;
        this.songName = songName;
        this.songArtist = songArtist;
        this.songAlbum = songAlbum;
        this.songPath = songPath;
        
        int libSize = playlistses.size();
        int lastSongNum = this.getLastSongNum();
        this.songNum = lastSongNum + 1;
    }
    
    public Library(int songNum, Users users, String songName, String songArtist, String songAlbum, String songPath, Set playlistses) {
       this.songNum = songNum;
       this.users = users;
       this.songName = songName;
       this.songArtist = songArtist;
       this.songAlbum = songAlbum;
       this.songPath = songPath;
       this.playlistses = playlistses;
    }
   
    public int getLastSongNum() {
        List<Song> searchArray = new ArrayList<Song>(playlistses);
        int lastSongNum = 0;
        for(Song thisSong : searchArray){
            lastSongNum = thisSong.showSongNum(thisSong);
        }
        
        return lastSongNum;
    }
    
    public int getSongNum() {
        return this.songNum;
    }
    
    public void setSongNum(int songNum) {
        this.songNum = songNum;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getSongName() {
        return this.songName;
    }
    
    public void setSongName(String songName) {
        this.songName = songName;
    }
    public String getSongArtist() {
        return this.songArtist;
    }
    
    public void setSongArtist(String songArtist) {
        this.songArtist = songArtist;
    }
    public String getSongAlbum() {
        return this.songAlbum;
    }
    
    public void setSongAlbum(String songAlbum) {
        this.songAlbum = songAlbum;
    }
    public String getSongPath() {
        return this.songPath;
    }
    
    public void setSongPath(String songPath) {
        this.songPath = songPath;
    }
    public Set getPlaylistses() {
        return this.playlistses;
    }
    
    public void setPlaylistses(Set playlistses) {
        this.playlistses = playlistses;
    }




}


